version: '3.7'
services:
  web:
    expose:
      - "9000"
    build: ./web/docker/.
    image: emr-nginx-php-fpm
    ports:
      - 851:80
      - 8546:443
    volumes:
      - logvolume:/var/log
      - symfonyCacheVolume:/var/www/html/var/cache
      - ${PWD}/web/scripts:/var/www/html/scripts
      - type: bind
        source: ${PWD}/site
        target: /var/www/html
    privileged: true
    environment:
      ERRORS: 1
      APP_ENV: 'dev'
      RUN_SCRIPTS: 1
      SKIP_COMPOSER: 1
      PHP_MEM_LIMIT: 512MB
      ENABLE_XDEBUG: 1
      PHP_IDE_CONFIG: serverName=PHPSTORM

volumes:
  logvolume: {}
  symfonyCacheVolume: {}