version: '3.7'
services:
  redis:
    image: redis:6.2.6-alpine
    container_name: test_redis_cache
    hostname: redis
    ports:
      - "6378:6379"
    networks:
      - redis-net
    volumes:
      - cacheVolumn:/data

  db:
    container_name: sym6_db
    labels:
      - "EMR database"
    networks:
      - forhost
      - backend

  web:
    container_name: test_web
    privileged: true
    networks:
      - backend
      - redis-net

volumes:
  logvolume: {}
  cacheVolumn: {}

networks:
  cluster:
    driver: bridge
  forhost:
    internal: false
  backend:
    internal: true
  redis-net:
