framework:
    cache:
        #app: cache.adapter.redis
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(int:REDIS_PORT)%'

        pools:
            redis.cache:
                adapter: '%framework_cache_adapter%'
                provider: 'redis://%env(REDIS_HOST)%:%env(int:REDIS_PORT)%'
                default_lifetime: '%framework_cache_lifetime%'
                tags: true

